# Generated by Django 3.1.7 on 2021-02-23 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=200)),
                ('describe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Start', models.DateTimeField()),
                ('AllowNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=500)),
                ('stuNO', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='functionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('passWord', models.CharField(max_length=500)),
                ('realName', models.CharField(max_length=100)),
                ('auth', models.IntegerField(default=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xwareBackend.user')),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('result', models.CharField(max_length=200)),
                ('handleTime', models.DateTimeField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='xwareBackend.appointment')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='xwareBackend.functionary')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwareBackend.timeslot'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='xwareBackend.user'),
        ),
    ]
