# Generated by Django 3.1.7 on 2021-02-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xwareBackend', '0002_user_realname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='stuNO',
            new_name='NO',
        ),
    ]
