# Generated by Django 3.1.7 on 2021-02-25 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwareBackend', '0003_auto_20210224_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainProblemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='subProblemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=200)),
                ('mainType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xwareBackend.mainproblemtype')),
            ],
        ),
    ]
