# Generated by Django 3.1.7 on 2021-02-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwareBackend', '0004_auto_20210225_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproblemtype',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
