# Generated by Django 3.1.7 on 2021-02-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwareBackend', '0005_mainproblemtype_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='End',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
