# Generated by Django 3.1.7 on 2021-02-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwareBackend', '0006_auto_20210225_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='type',
        ),
        migrations.AddField(
            model_name='appointment',
            name='problemType',
            field=models.CharField(default='', max_length=200),
        ),
    ]
