# Generated by Django 3.1.7 on 2021-02-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwareBackend', '0007_auto_20210225_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='sourseInfo',
            field=models.JSONField(null=True),
        ),
    ]
