# Generated by Django 3.1.7 on 2021-02-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xwareBackend', '0008_appointment_sourseinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='applyTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='detectInfo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='detectProblemType',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='finalStatus',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='handleWay',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='handleTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
