# Generated by Django 3.1.7 on 2021-02-26 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xwareBackend', '0009_auto_20210226_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionary',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='xwareBackend.user'),
        ),
    ]
